### ISSUE TITLE
Just a doubt

### ISSUE THREAD

**Issue by manikamittal2898** [thevarunshah/Wild-KMP#1]
Hey!
I was looking at your code for a personal project but I am unable to clearly understand the logic for it. Moreover, I feel there is some error in the getDFA () function, as I think the loop in it should begin with i=1 and not i=2. I am getting incorrect output for the following case:
![image](https://user-images.githubusercontent.com/31413782/81933258-b6dd0980-960a-11ea-8621-36f812172441.png)
I'll be glad if you could clarify my doubt and help me in understanding the basic logic of this algorithm.
Thanks!

**Comment by thevarunshah** [comment]
hey, thanks for filing this - I've fixed the issue in the latest commit (ff1189ecfa21bbd2a827a05052137986d34a41eb)
